/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class LayoutTree {
  constructor()
  createNode(style: LayoutStyle): number
  insertChild(parent: number, child: number, index: number): void
  removeChild(parent: number, child: number): void
  removeNode(node: number): void
  setStyle(node: number, style: LayoutStyle): void
  setTextDimensions(node: number, width: number, height: number): void
  markDirty(node: number): void
  setDisplayNone(node: number): void
  setDisplayFlex(node: number): void
  computeLayout(root: number, width: number, height?: number | undefined | null): void
  getLayout(node: number): ComputedLayout
  getChildCount(node: number): number
}

export interface ComputedLayout {
  x: number
  y: number
  width: number
  height: number
  paddingTop: number
  paddingRight: number
  paddingBottom: number
  paddingLeft: number
  borderTop: number
  borderRight: number
  borderBottom: number
  borderLeft: number
}

export interface Dimension {
  value: number
  unit: string
}

export interface Edges {
  top?: number
  right?: number
  bottom?: number
  left?: number
}

export interface LayoutStyle {
  position?: string
  display?: string
  overflow?: string
  width?: Dimension
  height?: Dimension
  minWidth?: Dimension
  minHeight?: Dimension
  maxWidth?: Dimension
  maxHeight?: Dimension
  flexDirection?: string
  flexWrap?: string
  flexGrow?: number
  flexShrink?: number
  flexBasis?: Dimension
  alignItems?: string
  alignSelf?: string
  alignContent?: string
  justifyContent?: string
  margin?: Edges
  padding?: Edges
  border?: Edges
  gap?: number
  columnGap?: number
  rowGap?: number
}
