import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..', '..', '..')

const packageDirs = [
	'packages/react',
	'packages/vue',
	'packages/angular',
	'packages/solid',
	'packages/svelte',
	'packages/plugin',
	'packages/typescript-plugin',
	'internal/core',
	'internal/shared',
	'internal/css-parser',
]

const versions: Record<string, string> = {}

for (const dir of packageDirs) {
	const pkgPath = resolve(root, dir, 'package.json')
	try {
		const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
		if (pkg.name && pkg.version) {
			versions[pkg.name] = `^${pkg.version}`
		}
	} catch {
		console.warn(`Warning: could not read ${pkgPath}`)
	}
}

const output = `// Auto-generated by scripts/bake-versions.ts — do not edit
export const VERSIONS: Record<string, string> = ${JSON.stringify(versions, null, '\t')} as const
`

const outPath = resolve(__dirname, '..', 'src', 'versions.gen.ts')
writeFileSync(outPath, output)
console.log(
	`Baked ${Object.keys(versions).length} package versions to src/versions.gen.ts`
)
