// Auto-generated by scripts/bake-versions.ts — do not edit
export const VERSIONS: Record<string, string> = {
	'@wolf-tui/react': '^1.3.4',
	'@wolf-tui/vue': '^1.3.4',
	'@wolf-tui/angular': '^1.3.4',
	'@wolf-tui/solid': '^1.3.4',
	'@wolf-tui/svelte': '^1.1.4',
	'@wolf-tui/plugin': '^1.3.5',
	'@wolf-tui/typescript-plugin': '^1.1.4',
	'@wolf-tui/core': '^1.3.3',
	'@wolf-tui/shared': '^1.3.3',
	'@wolf-tui/css-parser': '^1.3.5',
} as const
